backend: # Required
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Required
public_folder: "/images/uploads" # Required
collections: # Required
  - name: "home" # Required. Used in routes, e.g., /admin/collections/blog
    label: "Homepage" # Required. Used in the UI
    folder: "src" # Required. The path to the folder where the documents are stored
    create: true # Important. Allow users to create new documents in this collection
    fields: # Required. The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog" # Required. Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Required. Used in the UI
    folder: "src/blog" # Required. The path to the folder where the documents are stored
    create: true # Important. Allow users to create new documents in this collection
    fields: # Required. The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    files:
      - name: "settings"
        label: "Meta Settings"
        file: "src/_data/site.json"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Author name, name: authorName, widget: string }
          - { label: Author URL, name: authorUrl, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Favicon, name: favicon, widget: string }
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Agenda"
        name: "agenda"
        file: "src/_data/agenda.yaml"
        fields:
          - label: Agenda Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Date, name: date, widget: string }
              - { label: Texte, name: texte, widget: string }
              - { label: Titre, name: titre, widget: string }
              - { label: Description, name: description, widget: string }
